# Generated by Django 4.2.17 on 2026-03-04 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fighters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('venue', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('sportradar_id', models.CharField(max_length=100, unique=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_class', models.CharField(max_length=50)),
                ('card_section', models.CharField(choices=[('main', 'Main Card'), ('co-main', 'Co-Main'), ('prelim', 'Prelims'), ('early', 'Early Prelims')], default='main', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('method', models.CharField(blank=True, default='', max_length=50)),
                ('final_round', models.IntegerField(blank=True, null=True)),
                ('final_time', models.CharField(blank=True, default='', max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights', to='events.event')),
                ('fighter_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights_as_a', to='fighters.fighter')),
                ('fighter_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights_as_b', to='fighters.fighter')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fights_won', to='fighters.fighter')),
            ],
            options={
                'ordering': ['card_section', 'order'],
            },
        ),
    ]
