# Generated by Django 4.2.17 on 2026-03-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, default='', max_length=100)),
                ('weight_class', models.CharField(max_length=50)),
                ('nationality', models.CharField(blank=True, default='', max_length=50)),
                ('record_wins', models.IntegerField(default=0)),
                ('record_losses', models.IntegerField(default=0)),
                ('record_draws', models.IntegerField(default=0)),
                ('wins_ko_tko', models.IntegerField(default=0)),
                ('wins_submission', models.IntegerField(default=0)),
                ('wins_decision', models.IntegerField(default=0)),
                ('losses_ko_tko', models.IntegerField(default=0)),
                ('losses_submission', models.IntegerField(default=0)),
                ('losses_decision', models.IntegerField(default=0)),
                ('avg_fight_time', models.FloatField(blank=True, null=True)),
                ('sig_strikes_per_min', models.FloatField(blank=True, null=True)),
                ('strike_accuracy', models.FloatField(blank=True, null=True)),
                ('takedown_avg', models.FloatField(blank=True, null=True)),
                ('takedown_accuracy', models.FloatField(blank=True, null=True)),
                ('takedown_defense', models.FloatField(blank=True, null=True)),
                ('sub_attempts_per_min', models.FloatField(blank=True, null=True)),
                ('sportradar_id', models.CharField(max_length=100, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
